format = """
$line_break\
[](surface0)\
$os\
$username\
$hostname\
[ ](bg:surface0)\
[](bg:color_blue fg:surface0)\
$directory\
[](fg:color_blue bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:green)\
$c\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
$lua\
[](fg:green bg:)\
$line_break$character\
"""

right_format = """
$status\
"""

add_newline = false
palette = 'my_palette'


[palettes.my_palette]
color_aqua = '#689d6a'
color_green = '#98971a'
color_blue = '#458588'
red = "#f38ba8"
green = "#6d9170"
text = "#cdd6f4"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"


[profiles]
transient="""
[> ]()\
"""
rtransient="""
$status\
"""


[status]
disabled = false
format = '[$status](fg:bold red)'


[os]
disabled = true
style = "bg:surface0 fg:text"


[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
Debian = "󰣚"


[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user]($style)'

[hostname]
ssh_only = true
style = "bg:surface0 fg:text"
format = '[@$hostname]($style)'

[directory]
style = "fg:mantle bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:color_green)]($style)'


[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:base bg:color_green)]($style)'


[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[rust]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[golang]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[php]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[kotlin]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[haskell]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[python]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[lua]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:base bg:green)]($style)'


[docker_context]
symbol = " "
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'


[character]
disabled = false
success_symbol = '[ ](bold fg:green)'
error_symbol = '[ ](bold fg:red)'
